name: GitHub Stats
description: Generate your github readme stats.
author: 'Wybxc'
inputs:
  output-action:
    description: Output action, must be 'commit', 'pull-request', 'gists', or 'none'
    required: false
    default: 'commit'
  repo:
    description: GitHub repository, e.g. Wybxc/github-stats. Default is the repository using the action.
    required: false
    default: ''
  branch:
    description: GitHub repository branch. Default is the master or main branch.
    required: false
    default: ''
  token:
    description: GitHub personal access token.
    required: true

  github-username:
    description: Your github username.
    required: false
    default: ''
  github-output-filename:
    description: The filename of the output svg file.
    required: false
    default: github-stats.svg
  github-image-width:
    description: The width of the image.
    required: false
    default: '495'
  github-card-title:
    description: The title of the github card. Default is `<username>'s GitHub Stats`.
    required: false
    default: ''
  github-include-collaborated-stargazers:
    description: Include stars from repositories of which you are collaborators.
    required: false
    default: 'true'
  github-only-last-year:
    description: Only show stats from the last year.
    required: false
    default: 'false'
  github-hide-stat-items:
    description: |
      Hide specified stat items. Accepted values are "stars", "commits", "prs", "issues", and "contributions".
      Split by comma(,) or by newlines.
    required: false
    default: ''

  wakatime-username:
    description: Your wakatime username.
    required: false
    default: ''
  wakatime-output-filename:
    description: The filename of the output svg file.
    required: false
    default: wakatime-stats.svg
  wakatime-image-width:
    description: The width of the image.
    required: false
    default: '495'
  wakatime-compact-layout:
    description: Use compact layout.
    required: false
    default: 'false'
  wakatime-card-title:
    description: The title of the card. Default is `<username>'s Wakatime Stats`.
    required: false
    default: ''
  wakatime-max-languages-count:
    description: The maximum number of languages to show. Default is to show all languages.
    required: false
    default: '0'
  wakatime-hide-languages:
    description: Hide specified languages. Case insensitive. Split by comma(,) or by newlines.
    required: false
    default: ''

  verbose:
    description: Verbose output. Default to 0.
    required: false
    default: '0'
runs:
  using: docker
  image: Dockerfile
